### ISSUE TITLE
Integration with Android Lint

### ISSUE THREAD

**Issue by indraneel76** [google/Accessibility-Test-Framework-for-Android#2]
Hi,
Can't this feature be integrated with Android Lint Tool and it can do it as part of static code analysis ..

That way i don't need to run any test .

**Comment by ataulm** [comment]
No, it's not sufficient because lint won't be able to interpret complex (but common) cases.

There are existing lint checks for accessibility, e.g. the missing content description on an ImageView but these are pretty dumb - at the point of analysis lint cannot tell that there is a content description being set programmatically on that layout, or if a different layout is used at runtime based on detection of a spoken feedback accessibility service.

Given there's 101 ways to do anything on Android, it's safer to keep these checks as close to the user layer as possible.

**Comment by caseyburkhardt** [comment]
Agree.  Certain accessibility issues are well suited to static analysis, but presently this project relies on evaluation of a runtime representation of an application's view hierarchy.
